# Introduction to R

See file: IntroRStat4Astro2019.pdf

In [6]:
install.packages('forecast')
install.packages('caschrono')
install.packages('tseries')
install.packages('astsa')
install.packages('ltsa')
install.packages('timeSeries')
install.packages('TSA')
install.packages('arfima')
install.packages('fracdiff')
install.packages('vars')


Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
also installing the dependencies ‘checkmate’, ‘Formula’, ‘latticeExtra’, ‘acepack’, ‘gridExtra’, ‘htmlTable’, ‘viridis’, ‘Hmisc’

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
also installing the dependencies ‘leaps’, ‘locfit’

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
also installing the dependencies ‘strucchange’, ‘sandwich’

Updating HTML index of packages in '.Library'
Making 'pa

In [7]:
library(ltsa)

In [8]:
install.packages('lomb')
install.packages('WaveletComp')
install.packages('Rlibeemd')

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [9]:
ls()

character(0)

In [17]:
## Variable assignment

a <- "Hello" ; a ; rm(a) ; a

[1] "Hello"

ERROR: Error in eval(expr, envir, enclos): object 'a' not found


In [18]:
## Functions

myfunction <- function(par=2) { par^2} # defines the function myfunction, define default value (optional)
myfunction
# prints the function myfunction
myfunction()
# execute myfunction with the default values of the parameters
myfunction(3)
# execute myfunction for the value "3" of the parameter

function(par=2) { par^2}

[1] 4

[1] 9

It is a (very) good idea to write your function in a file ```myfunction.R```. A function can be loaded by sourcing
the file ```source("myfunction.R")``` or running the defining script by copy and paste.

### Data types

#### Variables

In [16]:
#Vectors: the simplest data structure.
x = c(1,3,6:10)
x
x*2
length(x)
y = 2*x + 3
y[5] ; y[1:3] ; y[-3] ; y[c(1,7,5,3)]

[1]  1  3  6  7  8  9 10

[1]  2  6 12 14 16 18 20

[1] 7

[1] 19

[1]  5  9 15

[1]  5  9 17 19 21 23

[1]  5 23 19 15

In [20]:
#Lists: lists are a general form of vector in which the various elements need not be of the same type, 
#and are often themselves vectors or lists. Lists provide a convenient way to return the results of a 
#statistical computation.
A = matrix(1:15,ncol=5)
mylist=list(mat=A, text="testliste",vec=y)
attributes(mylist)
mylist[[2]]
mylist$text

$names
[1] "mat"  "text" "vec"

[1] "testliste"

[1] "testliste"

In [21]:
#Matrices: matrices or more generally arrays are multi-dimensional generalizations of vectors. In fact,
#they are vectors that can be indexed by two or more indices and will be printed in special ways.
A = matrix(1:15,ncol=5); A
B = matrix(1:15,nc=5,byrow=TRUE) ; B
A[1,3] ; A[,2] ; A[2,] ; A[1:3,1:3]
is.matrix(A)
as.list(A)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15

[1] 7

[1] 4 5 6

[1]  2  5  8 11 14

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] TRUE

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] 6

[[7]]
[1] 7

[[8]]
[1] 8

[[9]]
[1] 9

[[10]]
[1] 10

[[11]]
[1] 11

[[12]]
[1] 12

[[13]]
[1] 13

[[14]]
[1] 14

[[15]]
[1] 15

In [22]:
##Data frames: data frames are matrix-like structures, in which the columns can be of different types.
#Think of data frames as ‘data matrices’ with one row per observational unit but with (possibly) both
#numerical and categorical variables. Many experiments are best described by data frames: the treatments
#are categorical but the response is numeric.
t = c(147, 132, 156, 167, 156, 140)
p = c( 50, 46, 47, 62, 58, 45)
s = c("M","F","F","M","M","F")
H = data.frame(t,p,s)
H
str(H)
data(USArrests)
str(USArrests)
summary(USArrests)
tmp <- USArrests

#The attach function allows to access variables of a data.frame without calling the data.frame.
attach(tmp) # Beware: this command does not allow to modify the data!
mean(Murder)
Murder <- Murder/2
mean(Murder)
detach(tmp)

mean(tmp$Murder) # $ gives a specific collumn: column = df$column1
with(tmp,mean(Murder))

t   p  s
1 147 50 M
2 132 46 F
3 156 47 F
4 167 62 M
5 156 58 M
6 140 45 F

'data.frame':	6 obs. of  3 variables:
 $ t: num  147 132 156 167 156 140
 $ p: num  50 46 47 62 58 45
 $ s: Factor w/ 2 levels "F","M": 2 1 1 2 2 1
'data.frame':	50 obs. of  4 variables:
 $ Murder  : num  13.2 10 8.1 8.8 9 7.9 3.3 5.9 15.4 17.4 ...
 $ Assault : int  236 263 294 190 276 204 110 238 335 211 ...
 $ UrbanPop: int  58 48 80 50 91 78 77 72 80 60 ...
 $ Rape    : num  21.2 44.5 31 19.5 40.6 38.7 11.1 15.8 31.9 25.8 ...


     Murder          Assault         UrbanPop          Rape      
 Min.   : 0.800   Min.   : 45.0   Min.   :32.00   Min.   : 7.30  
 1st Qu.: 4.075   1st Qu.:109.0   1st Qu.:54.50   1st Qu.:15.07  
 Median : 7.250   Median :159.0   Median :66.00   Median :20.10  
 Mean   : 7.788   Mean   :170.8   Mean   :65.54   Mean   :21.23  
 3rd Qu.:11.250   3rd Qu.:249.0   3rd Qu.:77.75   3rd Qu.:26.18  
 Max.   :17.400   Max.   :337.0   Max.   :91.00   Max.   :46.00  

[1] 7.788

[1] 3.894

[1] 7.788

[1] 7.788

In [23]:
# Indices

d = c(2,3,5,8,4,6); d
d[2]
d[2:3]
d[-3]
d[-(1:2)];d[-c(1,2)]
(1:length(d))[d>5]
which(d>5)

[1] 2 3 5 8 4 6

[1] 3

[1] 3 5

[1] 2 3 8 4 6

[1] 5 8 4 6

[1] 5 8 4 6

[1] 4 6

[1] 4 6